/* ─── Forjit AI · History + Gallery Panels ─────────────────────────────────
 *  Two separate export components sharing the same file.
 *  Pure UI — data + handlers come from App.jsx as props.
 * ──────────────────────────────────────────────────────────────────────────*/

import React from "react";
import { GitBranch } from "lucide-react";
import { TABS } from "../constants";

/* ── User's own generation history ─────────────────────────────────────── */
export function HistoryPanel({ history, currentId, loadFromHistory }) {
  if (history.length === 0) {
    return (
      <div className="text-center text-stone-500 text-sm p-8 font-mono">
        Nothing yet. Generate something!
      </div>
    );
  }
  return (
    <div className="space-y-2">
      {history.map((item) => (
        <button
          key={item.id}
          onClick={() => loadFromHistory(item)}
          className={`w-full text-left p-3 rounded-lg border transition ${
            currentId === item.id
              ? "border-amber-400/40 bg-amber-400/5"
              : "border-stone-800 hover:border-stone-700 hover:bg-stone-800/40"
          }`}
        >
          <div className="flex items-center gap-1.5 mb-1">
            {item.tab && (
              <span className="text-[9px] font-mono uppercase px-1.5 py-0.5 rounded bg-stone-800 text-stone-400">
                {TABS[item.tab]?.label || item.tab}
              </span>
            )}
            {item.subType && (
              <span className="text-[9px] font-mono px-1.5 py-0.5 rounded bg-stone-800/60 text-stone-500">
                {item.subType}
              </span>
            )}
            {item.isIteration && (
              <span className="text-[9px] font-mono uppercase px-1.5 py-0.5 rounded bg-emerald-500/15 text-emerald-300 flex items-center gap-0.5">
                <GitBranch className="w-2.5 h-2.5" />iter
              </span>
            )}
          </div>
          <div className="text-sm text-stone-200 line-clamp-2 mb-1">
            {item.isIteration ? item.parentChange : item.prompt}
          </div>
          <div className="text-[10px] font-mono text-stone-500">
            {new Date(item.ts).toLocaleString()} · {item.model}
          </div>
        </button>
      ))}
    </div>
  );
}

/* ── Community gallery (all users' public generations) ──────────────────── */
export function GalleryPanel({ repository, loadFromHistory }) {
  if (repository.length === 0) {
    return (
      <div className="text-center text-stone-500 text-sm p-8 font-mono">
        Gallery is empty. Generate and sign in to contribute!
      </div>
    );
  }
  return (
    <>
      <p className="text-xs text-stone-400 mb-3">
        Public content generated by all users. Click to preview and reuse.
      </p>
      <div className="space-y-2">
        {repository.map((item) => (
          <button
            key={item.id}
            onClick={() => loadFromHistory(item)}
            className="w-full text-left p-3 rounded-lg border border-stone-800 hover:border-amber-400/40 hover:bg-amber-400/5 transition"
          >
            <div className="flex items-center gap-1.5 mb-1 flex-wrap">
              {item.tab && (
                <span className="text-[9px] font-mono uppercase px-1.5 py-0.5 rounded bg-stone-800 text-stone-400">
                  {TABS[item.tab]?.label}
                </span>
              )}
              <span className="text-[10px] text-stone-500">by {item.userName}</span>
            </div>
            <div className="text-sm text-stone-200 line-clamp-2">{item.prompt}</div>
            <div className="text-[10px] font-mono text-stone-600 mt-1">
              {new Date(item.ts).toLocaleDateString()}
            </div>
          </button>
        ))}
      </div>
    </>
  );
}
